-- Base ultra-complète d'exercices (100+)
insert into exercises (name, muscle_group, equipment) values
-- JAMBES : Quadriceps
('Squat', 'Jambes', 'Barre'),
('Squat avant', 'Jambes', 'Barre'),
('Squat gobelet', 'Jambes', 'Haltères'),
('Fentes marchées', 'Jambes', 'Haltères'),
('Fentes bulgares', 'Jambes', 'Haltères'),
('Presse à cuisses', 'Jambes', 'Machine'),
('Hack squat', 'Jambes', 'Machine'),
('Leg extension', 'Jambes', 'Machine'),
('Sissy squat', 'Jambes', 'Poids du corps'),
('Split squat', 'Jambes', 'Haltères'),
-- JAMBES : Ischios
('Soulevé de terre jambes tendues', 'Jambes', 'Barre'),
('Soulevé de terre roumain', 'Jambes', 'Barre'),
('Leg curl allongé', 'Jambes', 'Machine'),
('Leg curl assis', 'Jambes', 'Machine'),
('Good morning', 'Jambes', 'Barre'),
('Hip thrust', 'Jambes', 'Barre'),
('Glute bridge', 'Jambes', 'Poids du corps'),
('Nordic curl', 'Jambes', 'Poids du corps'),
-- JAMBES : Fessiers
('Hip thrust', 'Jambes', 'Barre'),
('Glute bridge', 'Jambes', 'Poids du corps'),
('Abduction machine', 'Jambes', 'Machine'),
('Kickback poulie', 'Jambes', 'Poulie'),
('Step up', 'Jambes', 'Haltères'),
-- JAMBES : Mollets
('Mollets debout', 'Jambes', 'Machine'),
('Mollets assis', 'Jambes', 'Machine'),
('Mollets à la presse', 'Jambes', 'Machine'),
('Mollets unilatéral', 'Jambes', 'Poids du corps'),
-- PECTORAUX
('Développé couché', 'Pectoraux', 'Barre'),
('Développé incliné', 'Pectoraux', 'Barre'),
('Développé décliné', 'Pectoraux', 'Barre'),
('Développé haltères', 'Pectoraux', 'Haltères'),
('Développé machine', 'Pectoraux', 'Machine'),
('Écarté couché', 'Pectoraux', 'Haltères'),
('Écarté incliné', 'Pectoraux', 'Haltères'),
('Écarté poulie', 'Pectoraux', 'Poulie'),
('Dips', 'Pectoraux', 'Poids du corps'),
('Pompes', 'Pectoraux', 'Poids du corps'),
('Pec deck', 'Pectoraux', 'Machine'),
('Pull-over', 'Pectoraux', 'Haltères'),
-- DOS : Largeur
('Tractions pronation', 'Dos', 'Poids du corps'),
('Tractions supination', 'Dos', 'Poids du corps'),
('Tirage vertical', 'Dos', 'Machine'),
('Tirage horizontal', 'Dos', 'Machine'),
('Rowing poulie basse', 'Dos', 'Poulie'),
('Rowing unilatéral haltère', 'Dos', 'Haltères'),
('Rowing barre', 'Dos', 'Barre'),
('Rowing T-bar', 'Dos', 'Machine'),
('Pull-over poulie', 'Dos', 'Poulie'),
('Soulevé de terre', 'Dos', 'Barre'),
-- DOS : Épaisseur
('Rowing haltères', 'Dos', 'Haltères'),
('Rowing machine', 'Dos', 'Machine'),
('Shrugs', 'Dos', 'Haltères'),
('Face pull', 'Dos', 'Poulie'),
-- EPAULES : Faisceau antérieur
('Développé militaire', 'Épaules', 'Barre'),
('Développé haltères épaules', 'Épaules', 'Haltères'),
('Développé Arnold', 'Épaules', 'Haltères'),
-- EPAULES : Faisceau latéral
('Élévations latérales', 'Épaules', 'Haltères'),
('Élévations latérales poulie', 'Épaules', 'Poulie'),
-- EPAULES : Faisceau postérieur
('Oiseau', 'Épaules', 'Haltères'),
('Reverse pec deck', 'Épaules', 'Machine'),
('Rowing menton', 'Épaules', 'Barre'),
-- BICEPS
('Curl barre', 'Biceps', 'Barre'),
('Curl haltères', 'Biceps', 'Haltères'),
('Curl marteau', 'Biceps', 'Haltères'),
('Curl pupitre', 'Biceps', 'Haltères'),
('Curl concentration', 'Biceps', 'Haltères'),
('Curl poulie', 'Biceps', 'Poulie'),
('Curl inversé', 'Biceps', 'Barre'),
-- TRICEPS
('Barre front', 'Triceps', 'Barre'),
('Extension poulie', 'Triceps', 'Poulie'),
('Dips triceps', 'Triceps', 'Poids du corps'),
('Kickback', 'Triceps', 'Haltères'),
('Extension haltère nuque', 'Triceps', 'Haltères'),
('Pompes serrées', 'Triceps', 'Poids du corps'),
-- ABDOS
('Crunch', 'Abdos', 'Poids du corps'),
('Crunch poulie', 'Abdos', 'Poulie'),
('Relevé de jambes', 'Abdos', 'Poids du corps'),
('Gainage', 'Abdos', 'Poids du corps'),
('Russian twist', 'Abdos', 'Haltères'),
('Mountain climber', 'Abdos', 'Poids du corps'),
('Planche', 'Abdos', 'Poids du corps'),
('Crunch oblique', 'Abdos', 'Poids du corps'),
('Vacuum', 'Abdos', 'Poids du corps'),
-- CARDIO
('Course à pied', 'Cardio', 'Tapis'),
('Vélo', 'Cardio', 'Vélo'),
('Rameur', 'Cardio', 'Rameur'),
('Corde à sauter', 'Cardio', 'Corde'),
('Burpees', 'Cardio', 'Poids du corps'),
('Ski erg', 'Cardio', 'Machine'),
('Box jump', 'Cardio', 'Plyo box'),
('Battle rope', 'Cardio', 'Corde'),
('Escalier', 'Cardio', 'Escalier'),
('Air bike', 'Cardio', 'Vélo');
