-- Remplissage massif de la table exercises
insert into exercises (name, muscle_group, equipment) values
('Développé couché', 'Pectoraux', 'Barre'),
('Développé incliné', 'Pectoraux', 'Barre'),
('Développé décliné', 'Pectoraux', 'Barre'),
('Développé haltères', 'Pectoraux', 'Haltères'),
('Écarté couché', 'Pectoraux', 'Haltères'),
('Dips', 'Pectoraux', 'Poids du corps'),
('Pec deck', 'Pectoraux', 'Machine'),
('Pompes', 'Pectoraux', 'Poids du corps'),
('Pull-over', 'Pectoraux', 'Haltères'),

('Tractions pronation', 'Dos', 'Poids du corps'),
('Tractions supination', 'Dos', 'Poids du corps'),
('Rowing barre', 'Dos', 'Barre'),
('Rowing haltères', 'Dos', 'Haltères'),
('Rowing machine', 'Dos', 'Machine'),
('Tirage horizontal', 'Dos', 'Machine'),
('Tirage vertical', 'Dos', 'Machine'),
('Pull-over poulie', 'Dos', 'Poulie'),
('Soulevé de terre', 'Dos', 'Barre'),

('Développé militaire', 'Épaules', 'Barre'),
('Développé haltères épaules', 'Épaules', 'Haltères'),
('Élévations latérales', 'Épaules', 'Haltères'),
('Oiseau', 'Épaules', 'Haltères'),
('Face pull', 'Épaules', 'Poulie'),
('Shrugs', 'Épaules', 'Haltères'),

('Curl barre', 'Biceps', 'Barre'),
('Curl haltères', 'Biceps', 'Haltères'),
('Curl marteau', 'Biceps', 'Haltères'),
('Curl pupitre', 'Biceps', 'Haltères'),
('Curl concentration', 'Biceps', 'Haltères'),
('Curl poulie', 'Biceps', 'Poulie'),

('Barre front', 'Triceps', 'Barre'),
('Extension poulie', 'Triceps', 'Poulie'),
('Dips triceps', 'Triceps', 'Poids du corps'),
('Kickback', 'Triceps', 'Haltères'),
('Extension haltère nuque', 'Triceps', 'Haltères'),

('Squat', 'Jambes', 'Barre'),
('Presse à cuisses', 'Jambes', 'Machine'),
('Fentes', 'Jambes', 'Haltères'),
('Leg extension', 'Jambes', 'Machine'),
('Leg curl', 'Jambes', 'Machine'),
('Soulevé de terre jambes tendues', 'Jambes', 'Barre'),
('Mollets debout', 'Jambes', 'Machine'),
('Mollets assis', 'Jambes', 'Machine'),

('Crunch', 'Abdos', 'Poids du corps'),
('Relevé de jambes', 'Abdos', 'Poids du corps'),
('Gainage', 'Abdos', 'Poids du corps'),
('Crunch poulie', 'Abdos', 'Poulie'),
('Russian twist', 'Abdos', 'Haltères'),
('Mountain climber', 'Abdos', 'Poids du corps'),

('Course à pied', 'Cardio', 'Tapis'),
('Vélo', 'Cardio', 'Vélo'),
('Rameur', 'Cardio', 'Rameur'),
('Corde à sauter', 'Cardio', 'Corde'),
('Burpees', 'Cardio', 'Poids du corps'),
('Ski erg', 'Cardio', 'Machine');
